version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: admin
    volumes:
      - .:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080